name = "RigidityTheoryTools"
uuid = "5b45e325-545f-4a0f-a688-890b70d0fa47"
authors = ["Sascha St√ºttgen <sascha.stuettgen@rwth-aachen.de> and contributors"]
version = "0.0.3"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
BracketAlgebras = "304cb2e1-bfe1-4bb6-af58-8b73a9a6b3c1"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GraphMakie = "1ecd5474-83a3-4783-bb4f-06765db800d2"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"

[compat]
GLMakie = "0.13.6"
GeometryBasics = "0.5.10"
GraphMakie = "0.6.2"
julia = "1.10.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
